name: Metrics
on:
  # Schedule updates (at 5 UTC every day)
  schedule: [{cron: "0 5 */1 * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'TDarkShadow/TDarkShadow'"
    steps:
      - name: Github Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Brussels
          repositories_forks: yes
          plugin_followup: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_languages: yes
          plugin_lines: yes
