name: Metrics
on:
  # Schedule updates (at 5 UTC every day)
  schedule: [{cron: "0 5 * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Github Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Brussels
          repositories_forks: yes
          plugin_gists: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_habits: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_visibility: public
          plugin_activity_filter: all
